services:
  authelia:
    image: authelia/authelia:4.39.16
    container_name: authelia
    ports:
      - "9091:9091"
    env_file:
      - ./authelia/vars.env
      - ./secrets.env # AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD, AUTHELIA_STORAGE_ENCRYPTION_KEY, AUTHELIA_NOTIFIER_SMTP_PASSWORD
    networks:
      - authelia_net
    restart: unless-stopped
    volumes:
      - ./authelia/config:/config
      - ./certs:/certs:ro
  redis:
    image: redis:8.6.2-alpine3.23
    container_name: authelia-redis
    restart: unless-stopped
    networks:
      - authelia_net
      
  semaphore:
    image: semaphoreui/semaphore:v2.17.26
    container_name: semaphore
    ports:
      - "3000:3000"
    env_file:
      - ./semaphore/vars.env
      - ./secrets.env # SEMAPHORE_OIDC_PROVIDERS, SEMAPHORE_ADMIN_PASSWORD
    restart: unless-stopped
    volumes:
      - semaphore_data:/var/lib/semaphore
      - semaphore_config:/etc/semaphore
      - semaphore_tmp:/tmp/semaphore
      - ./certs:/certs:ro
    networks:
      - authelia_net

  caddy:
    image: caddybuilds/caddy-cloudflare:2.11.2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./secrets.env # CLOUDFLARE_API_TOKEN
    restart: unless-stopped
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/usr/local/share/ca-certificates:ro
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts: 
      - "host.docker.internal:host-gateway"
    command: sh -c "update-ca-certificates && caddy run --config /etc/caddy/Caddyfile"
    networks:
      - authelia_net

  vaultwarden:
    image: vaultwarden/server:1.35.4-alpine
    container_name: vaultwarden
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - ./vaultwarden/vars.env
      - ./secrets.env # SSO_CLIENT_SECRET, ADMIN_TOKEN, SMTP_PASSWORD
    volumes:
      - ./vaultwarden/vw-data:/data
    networks:
      - authelia_net

volumes:
  semaphore_data:
  semaphore_config:
  semaphore_tmp:
  caddy_data:
  caddy_config:

networks:
  authelia_net:
    driver: bridge